### ISSUE TITLE
Remove __DEVELOPMENT__ constant

### ISSUE THREAD

**Issue by zalmoxisus** [jhen0409/react-chrome-extension-boilerplate#10]
Are any reasons of using webpack `__DEVELOPMENT__` constant while we have `process.env.NODE_ENV`? Doesn't uglify remove dead code in the latter case?

**Comment by jhen0409** [comment]
Thanks! but I think the `process.env.NODE_ENV` is unsuitable, because chrome extension isn’t node. :|

I would use `__DEVTOOLS__` and` __DEVTOOLS_EXT__` to use `redux-devtools` and `redux-devtools-extension` in the future.

**Comment by zalmoxisus** [comment]
Yes, it is fair, but about using together `__DEVELOPMENT__` and `process.env.NODE_ENV` meaning the same could be confusing. The pro for the latter is that our submodules (including react and redux) already use it.

Like we already may set `process.env.HOT` in the `react-transform-hmr`, we can use `process.env.DEVTOOLS`. But of course it's a matter of taste :)
