### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by apreg** [jhen0409/react-chrome-extension-boilerplate#14]
To make build command run under Windows I had to modify package.json like this:

```
"build": "set BABEL_ENV=production & gulp build",
```
same for the other:
```
"test:app": "set BABEL_ENV=test & mocha --recursive --compilers js:babel-core/register test/app",
```

**Comment by jhen0409** [comment]
Hey @apreg. I moved babel development config to webpack dev config, Indirectly solved this problem. :)

Also, I added AppVeyor build to Roadmap, we hoping to take into account Windows developers.

**Comment by apreg** [comment]
Thank you for your hard work.
