### ISSUE TITLE
Readme: unclear how to run in development

### ISSUE THREAD

**Issue by jforaker** [jhen0409/react-chrome-extension-boilerplate#16]
Please provide more information on how to run the project in development:

```
[13:42:14] Please allow `https://localhost:3000` connections in Google Chrome

[13:42:14] and load unpacked extensions with ./dev
```

In particular, what does "load unpacked extensions with `./dev`" mean?

How to run it without running the whole `npm run compress` and manually installing it via dragging it to `chrome://extensions/`?

**Comment by jhen0409** [comment]
Refer: https://github.com/jhen0409/react-chrome-extension-boilerplate#development
1. The `injectpage`is need `https` protocol on development mode, but we not have SSL certificate.
2. It discussed in the (https://github.com/zalmoxisus/browser-redux/issues/5). (Maybe we can change to that solution)

Also, [this getstarted](https://developer.chrome.com/extensions/getstarted#unpacked) can help you, I'll add link to readme and log.

**Comment by zalmoxisus** [comment]
The con of that solution is that you'll still get warnings in the console, which could be annoying. I tried to make Webpack to work on both https and http. The idea was to use automatically the protocol corresponding to the injected page, but didn't figure how to get hmr to work on both protocols.

**Comment by kenyeung128** [comment]
Hi, you could get the warning removed by this new flag in chrome.

1. go to the url: chrome://flags/#allow-insecure-localhost
2. click "enable" and restart chrome.

**Comment by brandonmp** [comment]
Having some trouble getting hot reloading to work here. I've set the flag as @kenyeung128  suggested, and my address bar doesn't show any https issues, but getting errors described below. Welcoming any ideas--I don't need hot reloading, but the console spam is a pain.

1. `https://localhost` refuses connection, and `https://localhost:3000` "unexpectedly closed connection," so neither will load

2. There's a non-stop spam every few seconds in console of:

```
abstract-xhr.js:132 GET https://localhost:3000/sockjs-node/info?t=1473981718281 net::ERR_CONNECTION_CLOSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21
client:101 [WDS] Disconnected!sock.onclose @ client:101EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:356
abstract-xhr.js:132 GET https://localhost:3000/sockjs-node/info?t=1473981720295 net::ERR_CONNECTION_CLOSEDAbstractXHRObject._start @ abstract-xhr.js:132(anonymous function) @ abstract-xhr.js:21
```
here's a screenie: 
![image](https://cloud.githubusercontent.com/assets/14139991/18570678/0cde308e-7b7a-11e6-9a6a-bf5ecd7c20b6.png)
