### ISSUE TITLE
Unable to reach momentumdash.com?

### ISSUE THREAD

**Issue by alesch** [jhen0409/react-chrome-extension-boilerplate#2]
Hi and thank you for this repo.

I am having troubles getting it to run.
- I'm running the dev-server
- I have loaded the unpacked extension
- I see the new tool button

but I get this stack trace on the console:

```javascript
POST https://stats.momentumdash.com/ingest 503 (Service Unavailable)
   Z.ajaxTransport.G.cors.t.crossDomain.send @ lib.min.js:4
   Z.extend.ajax @ lib.min.js:4submitStats @ app.min.js:5
   (anonymous function) @ app.min.js:9
   Z.Callbacks.l @ lib.min.js:2
   Z.Callbacks.h.fireWith @ lib.min.js:2
   Z.extend.ready @ lib.min.js:2o @ lib.min.js:1
```

Thank you!

**Comment by jhen0409** [comment]
Hi,
I don't understand your problem. Make sure you are open DevTools in this extension page?
