### ISSUE TITLE
jslint: Arrow function used ambiguously with a conditional expression

### ISSUE THREAD

**Issue by tommedema** [jhen0409/react-chrome-extension-boilerplate#34]
Since `npm run lint` is one of the commands of this boilerplate, it would be a good idea to deal with all jslint errors. I'm having issues resolving this:

```
/app/components/MainSection.js
  73:41  error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow
```

The relevant code is:

```
const completedCount = todos.reduce((count, todo) =>
      todo.completed ? count + 1 : count,
      0
    );
```

It seems as though jslint doesn't like arrow functions with a conditional expression. I've tried other ways, such as a traditional function, but these resulted in other jslint errors.

**Comment by jhen0409** [comment]
Hey Tom, thank you for report! It looks related to [this](https://github.com/airbnb/javascript/commit/5ded256d3fab29b7b3fa42238093b9af632fb32b), it enabled [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow), and it released by `eslint-config-airbnb@6.2.0`.

I'll fix these with:
```js
(count, todo) => (todo.completed ? count + 1 : count)
```
