### ISSUE TITLE
TravisCI fails

### ISSUE THREAD

**Issue by tommedema** [jhen0409/react-chrome-extension-boilerplate#35]
I'm using the [.travis.yml](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/.travis.yml) file from master, and enabled the repo at travis-ci.com. 

The Travis build fails, not having changed the boilerplate.

The error is:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 google-chrome-stable : Depends: lsb-base (>= 4.1) but 4.0-0ubuntu20.3 is to be installed
```

See the [full log file here](https://gist.github.com/tommedema/8130e2752282c5e3cf4a2546035abc82).

**Comment by jhen0409** [comment]
It seems related to [this comment](https://github.com/travis-ci/apt-source-whitelist/pull/257#issuecomment-207425280), and `google-chrome-stable` also fails now.

**Comment by gauntface** [comment]
You can upgrade your VM from Ubuntu 12.04 to 14.04 by following info here: https://docs.travis-ci.com/user/trusty-ci-environment/

This fixed the issue on my Travis builds.

**Comment by tommedema** [comment]
Using trusty also works for me.

**Comment by jhen0409** [comment]
Close via #36.
