### ISSUE TITLE
Error font url at development mode

### ISSUE THREAD

**Issue by manhhailua** [jhen0409/react-chrome-extension-boilerplate#46]
![error](http://i652.photobucket.com/albums/uu246/Manhhailua/Screen%20Shot%202016-07-08%20at%2010.19.35%20AM_zpsep6miwqh.png)
I use bootstrap-loader in my project and got this error.

**Comment by jhen0409** [comment]
Should fixed. Thanks for report! :)

**Comment by manhhailua** [comment]
Awesome!
