### ISSUE TITLE
ERR_FILE_NOT_FOUND for inject

### ISSUE THREAD

**Issue by rubenpa** [jhen0409/react-chrome-extension-boilerplate#49]
I am trying to work on the inject script, but I keep getting the error:

`chrome-extension://pheloakanjmafejdhjgcgfbcdlladodf/js/inject.bundle.js net::ERR_FILE_NOT_FOUND`

I haven't changed the inject.js at all other than changing the id for the extension, so am unsure of what the issue may be.  Any ideas?

Thanks

**Comment by skyiea** [comment]
The issue is that `inject.bundle.js` doesn't exist within `.crx` file (that's where your path is linking). Assuming that you are using *dev*-build, this file should be available via `localhost:3000/js/`.

**Comment by jhen0409** [comment]
The `js/inject.bundle.js` should be inject by [background](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/extension/background/inject.js#L10), and it's disallow access for production, if you want allow access for other pages, you should add `js/inject.bundle.js` to [`web_accessible_resources`](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/manifest.prod.json#L15).
