### ISSUE TITLE
What does chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/inject.bundle.js') come from?

### ISSUE THREAD

**Issue by sammkj** [jhen0409/react-chrome-extension-boilerplate#50]
Hello there! Thank you for creating this boilerplate. It has been tremendously useful to me! I'm trying to dig deep into the code and I found this:

```
chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/inject.bundle.js')
```

in multiple files like `chrome/extension/background/inject.js` and jade templates under `/chrome/views`. I removed it and it didn't seem it's affecting anything. So is it safe to remove it?

**Comment by jhen0409** [comment]
Hey. :D It's inject script of `redux-devtools-extension`, if you have installed this would be useful, see https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/FAQ.md#how-to-include-it-in-chrome-apps-and-extensions.

**Comment by sammkj** [comment]
Ah! Thanks for telling me.

**Comment by zalmoxisus** [comment]
We could rename it to something more intuitive like `chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/redux-devtools-extension.js`, but it would be a breaking change.
