### ISSUE TITLE
Chrome extension doesn't work in dev mode

### ISSUE THREAD

**Issue by lightninglu10** [jhen0409/react-chrome-extension-boilerplate#54]
Hey guys, I'm trying to run the chrome extension in dev mode.

I've done everything the instructions say, and everything works EXCEPT the todo app.

When I load the production version with npm run build, I get the todo app, but when I do npm run dev and load the dev folder, the todo app is blank.

Attaching images below. Any idea why?
<img width="512" alt="screen shot 2016-11-12 at 3 22 41 pm" src="https://cloud.githubusercontent.com/assets/2453737/20242665/e4a12c80-a8eb-11e6-9481-1e5ccf75494b.png">
<img width="1400" alt="screen shot 2016-11-12 at 3 22 36 pm" src="https://cloud.githubusercontent.com/assets/2453737/20242664/e4a0c7a4-a8eb-11e6-9976-764ecbed6dbc.png">

**Comment by lightninglu10** [comment]
Also, unrelated but is there anyway to connect the inject.js through redux with the app components?  Getting stumped there. I want to pass data I'm getting through inject.js to the App.js components.

**Comment by jhen0409** [comment]
Hi @lightninglu10, thanks for report!

I'm found the problem, it looks related to redux-devtools-extension:

![2016-11-13 4 39 54](https://cloud.githubusercontent.com/assets/3001525/20244492/e07dc120-a9bf-11e6-9036-1cb704e33a5a.png)

/cc @zalmoxisus

**Comment by lightninglu10** [comment]
Is the solution for now to remove the redux-dev-tools portion?

**Comment by jhen0409** [comment]
You can remove [popup.pug#L12-L13](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/views/popup.pug#L12-L13) first (and [window](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/views/window.pug), [inject](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/views/inject.pug)), and check it work.

**Comment by jhen0409** [comment]
Ah, just my fault, I missing object [here](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/app/store/configureStore.dev.js#L9-L11), I'll fix it. 😂

**Comment by lightninglu10** [comment]
@jhen0409 

Bringing this up again:

"Also, unrelated but is there anyway to connect the inject.js through redux with the app components? Getting stumped there. I want to pass data I'm getting through inject.js to the App.js components."

Would you know how to do this?

**Comment by jhen0409** [comment]
> Also, unrelated but is there anyway to connect the inject.js through redux with the app components? Getting stumped there. I want to pass data I'm getting through inject.js to the App.js components.

Currently the inject page used iframe for CSS isolation, but pass data to App container will be difficult (may use postMessage of iframe or background), so it's not a good example.

Actually I'm Investigating [ReactShadow](https://github.com/Wildhoney/ReactShadow) to replace iframe, just not enough time.

**Comment by lightninglu10** [comment]
If I don't care for CSS isolation, can I just import the component directly into the inject page?

**Comment by jhen0409** [comment]
@lightninglu10 yeah, just replace [here](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/extension/inject.js#L27-L35).
