### ISSUE TITLE
cannot GET

### ISSUE THREAD

**Issue by johnrosenbaud11** [jhen0409/react-chrome-extension-boilerplate#62]
Hello there, I installed the boilerplate and it works, rendering the toDoApp, however, when I open a tab on port 3000, it says Cannot GET / : 

![image](https://cloud.githubusercontent.com/assets/25225045/23094206/b67cfa40-f5c2-11e6-968e-58a2530cc74c.png)

this is terminal webpack output:

![image](https://cloud.githubusercontent.com/assets/25225045/23094212/cd55dfca-f5c2-11e6-8da5-c65a59ff7599.png)

Is anyone else experiencing the same issue? Any suggestions on how to tackle this?

**Comment by jhen0409** [comment]
It's expected, the dev server just provides `http://localhost:3000/js/*.bundle.js` for the [extension usage](https://github.com/jhen0409/react-chrome-extension-boilerplate#examples) on development mode.

**Comment by johnrosenbaud11** [comment]
Thanks a lot. I am trying to add a  ` chrome.runtime.onMessage.addListener()` in background.js, I placed everywhere in the page but does not work, do you have any tips on where specifically should be placed?
