### ISSUE TITLE
`inject.js` is actually redundant.

### ISSUE THREAD

**Issue by Axure** [jhen0409/react-chrome-extension-boilerplate#64]
There is actually no content script injected I think. No such field in `manifest.json`, and the bundle file is not actually written to disk.

**Comment by jhen0409** [comment]
Duo to I want to load inject bundle from webpack dev server, so we do that in the [background script](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/extension/background/inject.js) (production also), so no content scripts in the `manifest.json`. You can see the bundle file with `npm run build`.

**Comment by yuejiaozhs** [comment]
Can "inject.bundle.js" be used directly? quite new about Chrome Extension and webpack, I tried many times but cannot insert TodoApp in existing webpage.
