### ISSUE TITLE
allow extension for all urls? 

### ISSUE THREAD

**Issue by johnrosenbaud11** [jhen0409/react-chrome-extension-boilerplate#67]
I am trying to allow the extension to work on all websites.

I modified the manifest.json (including the dev version) adding necessary permissions:
`"permissions": [ "contextMenus", "management", "tabs", "storage", "https://*/*", "<all_urls>" ],`

but it doesn't help, it won't work. Apparently it only works on github, and the matter is dealt with by this variable, which, would only work for github.com (tried replacing it with other websites, won't work)

`const arrowURLs = ['^https://github\\.com'];`

any clues?

Thanks,

**Comment by nickweinberg** [comment]
I did this:
```
chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
  if (changeInfo.status !== 'loading') {
    return;
  }

  const result = await isInjected(tabId);
  if (chrome.runtime.lastError || result[0]) return;

  loadScript('inject', tabId, () => console.log('load inject bundle success!'));
});
```

**Comment by tcr-nyt** [comment]
@nickweinberg Do you think you could expand on this? Not sure what this code does, and would really like to know the reasoning behind it!

**Comment by jhen0409** [comment]
Yeah you can modify [`chrome/extension/background/inject.js`](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/extension/background/inject.js#L33-L36).

**Comment by createbuildship** [comment]
I got stuck as this did not work for me

**Comment by e1jo** [comment]
> I got stuck as this did not work for me

try to add this on background.js (i pass empty object and this helped me)

  `chrome.runtime.onInstalled.addListener(function () {
        chrome.declarativeContent.onPageChanged.removeRules(undefined, function () {
            chrome.declarativeContent.onPageChanged.addRules([{
                conditions: [new chrome.declarativeContent.PageStateMatcher({})],
                actions: [new chrome.declarativeContent.ShowPageAction()]
                }
            ]);
        });
    });`
