### ISSUE TITLE
Misplaced elements at first display

### ISSUE THREAD

**Issue by stephanebruckert** [jhen0409/react-chrome-extension-boilerplate#69]
After a simple click on the extension icon, the elements inside the popup are all displayed in a messy order, until I start using it by clicking anywhere in the popup.

The weird thing is that I took a screenshot and all seems fine on it! 

Just wanted to know if you see what I mean (if it happens, it's quite obvious to notice)?

On Mac and my Chrome is up-to-date.

**Comment by thundergolfer** [comment]
I installed and started it up today on Mac OSX Sierra with up-to-date Chrome and experienced the same issue.

**Comment by HaveF** [comment]
I do suppose it maybe load page, css things, and render finally.

**Comment by stephanebruckert** [comment]
This looks fixed on my side. I can't reproduce it with and up-to-date Chrome. Built with stable Node
