### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by nyilmaz** [jhen0409/react-chrome-extension-boilerplate#82]
Would you consider upgrading project to webpack 2? Or I am planning to prepare a PR about this if you are willing to review. Let us know please.

**Comment by jhen0409** [comment]
Yeah I'll review for any PRs, thanks!

**Comment by rrfaria** [comment]
The better is not to upgrade to webpack 3 ?

**Comment by jhen0409** [comment]
Closed via #92, we have upgraded to webpack 3.
